feat: CephFS implementation to set directory quotas
lablup/backend.ai-storage-proxy pull request #16
Opened 2020-12-21 02:24 UTC by leksikov

Feature implementation and solution for issue _CephFS quota support_ [#237](https://github.com/lablup/backend.ai/issues/237) and part of [#50](https://github.com/lablup/backend.ai/issues/50).

After the CephFS is installed and vfolder directory is set and mounted. Storage proxy can create folders in designated directory and set the quotas limits.

2021-01-08 08:24 UTC, leksikov commented
Build an installation script for deploying and testing ceph-cluster with storage proxy.

2021-01-10 12:07 UTC, leksikov commented
Recent commit provides functionality to create folder on CephFS mounted ceph-fuse volume directory. 
While creating a directory it sets a quota. However, quota functionality cannot be completely tested due to operation not supported issue from setfattr.

2021-03-27 06:04 UTC, adrysn requested changes
I have some question on the code for the initial review.

I also think that it would be better to use Ceph REST API to execute commands, but I think I need some time to study about it.

2021-03-29 12:20 UTC, leksikov commented on src/ai/backend/storage/cephfs/__init__.py
> +        await run(f"sudo  chmod 777 -R {vfpath}")
Without setting chmod rights to newly created folder there is an execution error raised ai.backend.storage.exception.ExecutionError: setfattr: /mnt/vfroot/ceph-fuse/b0/72/9c4d2b3f4cfd9aa178d29117f806: Permission denied.

Setting rights for whole ceph-fuse directory doesn't solve the issue while setting rights at the moment of creation fix the problem.

2021-03-29 12:22 UTC, leksikov commented on src/ai/backend/storage/cephfs/__init__.py
> +        await self.set_quota(vfpath, 100000000)
Made the quota variable for setting quota function

2022-10-19 01:34 UTC, closed without merging