Rewrite xfs using vfs as the base
lablup/backend.ai-storage-proxy pull request #2
Opened 2020-08-26 01:10 UTC by yongkyunlee

Updated code for xfs with vfs as the base.
Referenced FlashBladeVolume.

Regarding getting usage, when I use xfs_quota report functionality, it says the usage is 4k, which is the size of a block, even if I write 3 bytes, so I did not add tests for getting usage.

Helpful resource related to xfs_quota: http://manpages.ubuntu.com/manpages/cosmic/man8/xfs_quota.8.html

2020-09-03 09:23 UTC, achimnol requested changes

2020-09-03 09:23 UTC, achimnol commented on src/ai/backend/storage/xfs/__init__.py
> +            return
This part should raise explicit errors which is wrapped as HTTP error responses in the manager-facing API layer. You may define additional package-level exceptions.

2020-09-03 09:23 UTC, achimnol commented on src/ai/backend/storage/types.py
> +            t.Key('bsize', default=''): t.String,
You could use `ai.backend.common.validators.BinarySize` for explicit conversion of human-readable byte-size string representations into integers.

2020-09-09 02:17 UTC, yongkyunlee commented
Merging PR lablup/backend.ai-storage-proxy#5 into this PR

2020-09-25 08:04 UTC, achimnol approved these changes

2020-09-25 08:56 UTC, merged